version: '3.4'

services:
  postgres:
    image: postgres:13.4
    container_name: getshop_postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./db-docker:/docker-entrypoint-initdb.d
    env_file:
      - '.env'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: 'default'
      POSTGRES_USER: 'postgres'

    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  api:
    image: getshop-api
    container_name: getshop-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DB_HOST: getshop_postgres
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    networks:
      - default
    command: npm run start:dev

volumes:
  postgresdb:
networks:
  default:
