version: '3.4'

services:
  postgres:
    image: postgres:13.4
    container_name: getshop_postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./db-docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: 'default'
      POSTGRES_USER: 'postgres'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'

    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  postgresdb:
